const lessonTitle = "秋天的怀念";

const lessonData = [
    // ===== 第1段 =====
    ["双腿", "shuāng tuǐ", "Both legs", "Kedua-dua kaki"],
    ["瘫痪后", "tān huàn hòu", "after paralysis", "selepas lumpuh"],
    ["，", "", "", ""],
    ["我的", "wǒ de", "my", "saya punya"],
    ["脾气", "pí qì", "temper", "perangai"],
    ["变得", "biàn de", "became", "menjadi"],
    ["暴怒无常", "bào nù wú cháng", "irritable and unpredictable", "mudah marah dan tidak menentu"],
    ["。", "", "", ""],
    ["望着望着", "wàng zhe wàng zhe", "gazing at", "memandang"],
    ["天上", "tiān shàng", "the sky", "langit"],
    ["北归的", "běi guī de", "northward-returning", "kembali ke utara"],
    ["雁阵", "yàn zhèn", "wild geese formation", "rombongan angsa liar"],
    ["，", "", "", ""],
    ["我会", "wǒ huì", "I would", "saya akan"],
    ["突然", "tū rán", "suddenly", "tiba-tiba"],
    ["把", "bǎ", "", ""],
    ["面前的", "miàn qián de", "in front of me", "di hadapan"],
    ["玻璃", "bō li", "glass", "kaca"],
    ["砸碎", "zá suì", "shatter", "memecahkan"],
    ["；", "", "", ""],
    ["听着听着", "tīng zhe tīng zhe", "listening to", "mendengar"],
    ["李谷一", "lǐ gǔ yī", "Li Guyi", "Li Guyi"],
    ["甜美的", "tián měi de", "sweet", "merdu"],
    ["歌声", "gē shēng", "singing voice", "suara nyanyian"],
    ["，", "", "", ""],
    ["我会", "wǒ huì", "I would", "saya akan"],
    ["猛地", "měng de", "violently", "dengan ganas"],
    ["把", "bǎ", "", ""],
    ["手边的", "shǒu biān de", "at hand", "di sisi tangan"],
    ["东西", "dōng xi", "things", "benda"],
    ["摔向", "shuāi xiàng", "throw at", "membaling ke"],
    ["四周的", "sì zhōu de", "surrounding", "sekeliling"],
    ["墙壁", "qiáng bì", "walls", "dinding"],
    ["。", "", "", ""],
    ["母亲", "mǔ qīn", "Mother", "Ibu"],
    ["就", "jiù", "would", "lalu"],
    ["悄悄地", "qiāo qiāo de", "quietly", "secara senyap"],
    ["躲出去", "duǒ chū qù", "slip out", "keluar"],
    ["，", "", "", ""],
    ["在我", "zài wǒ", "in my", "di tempat"],
    ["看不见的", "kàn bù jiàn de", "unseen", "yang tidak kelihatan"],
    ["地方", "dì fang", "place", "tempat"],
    ["偷偷地", "tōu tōu de", "secretly", "secara senyap"],
    ["听着", "tīng zhe", "listening to", "mendengar"],
    ["我的", "wǒ de", "my", "saya punya"],
    ["动静", "dòng jìng", "movements", "pergerakan"],
    ["。", "", "", ""],
    ["当", "dāng", "When", "Apabila"],
    ["一切", "yí qiè", "everything", "segala-galanya"],
    ["恢复", "huī fù", "returned to", "kembali"],
    ["沉寂", "chén jì", "silence", "kesunyian"],
    ["，", "", "", ""],
    ["她", "tā", "she", "dia"],
    ["又", "yòu", "again", "lagi"],
    ["悄悄地", "qiāo qiāo de", "quietly", "secara senyap"],
    ["进来", "jìn lái", "came in", "masuk"],
    ["，", "", "", ""],
    ["眼边", "yǎn biān", "the corners of her eyes", "hujung mata"],
    ["红红的", "hóng hóng de", "red", "merah"],
    ["，", "", "", ""],
    ["看着", "kàn zhe", "looking at", "memandang"],
    ["我", "wǒ", "me", "saya"],
    ["。", "", "", ""],
    ["“", "", "", ""],
    ["听说", "tīng shuō", "I heard", "Saya dengar"],
    ["北海的", "běi hǎi de", "Beihai's", "Beihai punya"],
    ["花儿", "huā r", "flowers", "bunga-bungaan"],
    ["都开了", "dōu kāi le", "have all bloomed", "telah mekar"],
    ["，", "", "", ""],
    ["我推着", "wǒ tuī zhe", "I'll push", "Saya tolak"],
    ["你去走走", "nǐ qù zǒu zǒu", "you for a walk", "awak pergi berjalan"],
    ["。”", "", "", ""],
    ["她", "tā", "She", "Dia"],
    ["总是", "zǒng shì", "always", "selalu"],
    ["这么说", "zhè me shuō", "said this", "berkata begitu"],
    ["。", "", "", ""],
    ["母亲", "mǔ qīn", "Mother", "Ibu"],
    ["喜欢花", "xǐ huān huā", "loved flowers", "suka bunga"],
    ["，", "", "", ""],
    ["可", "kě", "but", "tetapi"],
    ["自从", "zì cóng", "since", "sejak"],
    ["我的腿", "wǒ de tuǐ", "my legs", "kaki saya"],
    ["瘫痪后", "tān huàn hòu", "after paralysis", "selepas lumpuh"],
    ["，", "", "", ""],
    ["她", "tā", "she", "dia"],
    ["侍弄的", "shì nòng de", "the ones she tended", "yang dijaganya"],
    ["那些花", "nà xiē huā", "those flowers", "bunga-bunga itu"],
    ["都死了", "dōu sǐ le", "all died", "semua mati"],
    ["。", "", "", ""],
    ["“", "", "", ""],
    ["不", "bù", "No", "Tidak"],
    ["，", "", "", ""],
    ["我不去", "wǒ bù qù", "I won't go", "Saya tidak mahu pergi"],
    ["！”", "", "", ""],
    ["我", "wǒ", "I", "Saya"],
    ["狠命地", "hěn mìng de", "furiously", "dengan ganas"],
    ["捶打", "chuí dǎ", "beat", "memukul"],
    ["这两条", "zhè liǎng tiáo", "these two", "kedua-dua"],
    ["可恨的", "kě hèn de", "hateful", "yang dibenci"],
    ["腿", "tuǐ", "legs", "kaki"],
    ["，", "", "", ""],
    ["喊着", "hǎn zhe", "shouting", "berteriak"],
    ["：", "", "", ""],
    ["“", "", "", ""],
    ["我可", "wǒ kě", "What's the point", "Apa gunanya"],
    ["活什么劲", "huó shén me jìn", "of living", "hidup"],
    ["！”", "", "", ""],
    ["母亲", "mǔ qīn", "Mother", "Ibu"],
    ["扑过来", "pū guò lái", "rushed over", "meluru ke mari"],
    ["抓住", "zhuā zhù", "grabbed", "memegang"],
    ["我的", "wǒ de", "my", "saya punya"],
    ["手", "shǒu", "hands", "tangan"],
    ["，", "", "", ""],
    ["忍住", "rěn zhù", "holding back", "menahan"],
    ["哭声说", "kū shēng shuō", "tearfully said", "berkata dengan tangisan"],
    ["：", "", "", ""],
    ["“", "", "", ""],
    ["咱娘儿俩", "zán niáng r liǎ", "The two of us", "Kita berdua"],
    ["在一块儿", "zài yī kuài r", "together", "bersama"],
    ["，", "", "", ""],
    ["好好儿活", "hǎo hǎo r huó", "live well", "hidup dengan baik"],
    ["，", "", "", ""],
    ["好好儿活", "hǎo hǎo r huó", "live well", "hidup dengan baik"],
    ["……”", "", "", ""],

    ["\n", "", "", ""], // 👈 第2段

    ["可", "kě", "But", "Tetapi"],
    ["我", "wǒ", "I", "Saya"],
    ["却", "què", "however", "sebaliknya"],
    ["一直", "yì zhí", "always", "sentiasa"],
    ["都", "dōu", "", ""],
    ["不知道", "bù zhī dào", "didn't know", "tidak tahu"],
    ["，", "", "", ""],
    ["她的", "tā de", "her", "dia punya"],
    ["病", "bìng", "illness", "penyakit"],
    ["已经", "yǐ jīng", "already", "sudah"],
    ["到了", "dào le", "reached", "sampai ke"],
    ["那步田地", "nà bù tián dì", "that stage", "peringkat itu"],
    ["。", "", "", ""],
    ["后来", "hòu lái", "Later", "Kemudian"],
    ["妹妹", "mèi mei", "my younger sister", "adik perempuan"],
    ["告诉", "gào su", "told", "memberitahu"],
    ["我", "wǒ", "me", "saya"],
    ["，", "", "", ""],
    ["她", "tā", "she", "dia"],
    ["常常", "cháng cháng", "often", "sering"],
    ["肝疼得", "gān téng de", "liver ached so", "sakit hati sehingga"],
    ["整宿整宿", "zhěng xiǔ zhěng xiǔ", "whole nights", "sepanjang malam"],
    ["翻来覆去", "fān lái fù qù", "tossing and turning", "terkial-kial"],
    ["地", "de", "", ""],
    ["睡不了觉", "shuì bù liǎo jiào", "couldn't sleep", "tidak dapat tidur"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第3段

    ["那天", "nà tiān", "That day", "Hari itu"],
    ["我又", "wǒ yòu", "I again", "Saya lagi"],
    ["独自", "dú zì", "alone", "seorang diri"],
    ["坐", "zuò", "sat", "duduk"],
    ["在", "zài", "in", "di"],
    ["屋里", "wū lǐ", "the room", "bilik"],
    ["，", "", "", ""],
    ["看着", "kàn zhe", "watching", "melihat"],
    ["窗外的", "chuāng wài de", "outside the window", "di luar tingkap"],
    ["树叶", "shù yè", "leaves", "daun-daun"],
    ["“", "", "", ""],
    ["刷刷啦啦", "shuā shuā lā lā", "rustling", "berdesir"],
    ["”", "", "", ""],
    ["地", "de", "", ""],
    ["飘落", "piāo luò", "falling", "berguguran"],
    ["。", "", "", ""],
    ["母亲", "mǔ qīn", "Mother", "Ibu"],
    ["进来了", "jìn lái le", "came in", "masuk"],
    ["，", "", "", ""],
    ["挡在", "dǎng zài", "stood in front of", "menghalang di"],
    ["窗前", "chuāng qián", "the window", "hadapan tingkap"],
    ["：", "", "", ""],
    ["“", "", "", ""],
    ["北海的", "běi hǎi de", "Beihai's", "Beihai punya"],
    ["菊花", "jú huā", "chrysanthemums", "bunga kekwa"],
    ["开了", "kāi le", "have bloomed", "telah mekar"],
    ["，", "", "", ""],
    ["我推着", "wǒ tuī zhe", "I'll push", "Saya tolak"],
    ["你去看看吧", "nǐ qù kàn kan ba", "you to go see", "awak pergi lihat"],
    ["。”", "", "", ""],
    ["她", "tā", "Her", "Dia punya"],
    ["憔悴的", "qiáo cuì de", "haggard", "lesu"],
    ["脸上", "liǎn shàng", "face", "wajah"],
    ["现出", "xiàn chū", "showed", "menunjukkan"],
    ["央求般", "yāng qiú bān", "beseeching", "seperti merayu"],
    ["的", "de", "", ""],
    ["神色", "shén sè", "expression", "raut"],
    ["。", "", "", ""],
    ["“", "", "", ""],
    ["什么时候", "shén me shí hou", "When", "Bila"],
    ["？”", "", "", ""],
    ["“", "", "", ""],
    ["你要是愿意", "nǐ yào shì yuàn yì", "If you're willing", "Jika awak mahu"],
    ["，", "", "", ""],
    ["就明天", "jiù míng tiān", "then tomorrow", "esok"],
    ["？”", "", "", ""],
    ["她说", "tā shuō", "she said", "dia berkata"],
    ["。", "", "", ""],
    ["我的回答", "wǒ de huí dá", "My answer", "Jawapan saya"],
    ["已经", "yǐ jīng", "already", "sudah"],
    ["让", "ràng", "made", "membuatkan"],
    ["她", "tā", "her", "dia"],
    ["喜出望外了", "xǐ chū wàng wài le", "overjoyed", "sangat gembira"],
    ["。", "", "", ""],
    ["“", "", "", ""],
    ["好吧", "hǎo ba", "Alright", "Baiklah"],
    ["，", "", "", ""],
    ["就明天", "jiù míng tiān", "tomorrow then", "esoklah"],
    ["。”", "", "", ""],
    ["我说", "wǒ shuō", "I said", "Saya berkata"],
    ["。", "", "", ""],
    ["她", "tā", "She", "Dia"],
    ["高兴得", "gāo xìng de", "so happy", "begitu gembira"],
    ["一会儿坐下", "yí huì r zuò xià", "sat down", "duduk"],
    ["，", "", "", ""],
    ["一会儿站起", "yí huì r zhàn qǐ", "stood up", "berdiri"],
    ["：", "", "", ""],
    ["“", "", "", ""],
    ["那就", "nà jiù", "Then", "Kalau begitu"],
    ["赶紧", "gǎn jǐn", "hurry and", "cepat"],
    ["准备准备", "zhǔn bèi zhǔn bèi", "get ready", "bersiap-siap"],
    ["。”", "", "", ""],
    ["“", "", "", ""],
    ["唉呀", "āi yā", "Oh", "Alamak"],
    ["，", "", "", ""],
    ["烦不烦", "fán bù fán", "Are you annoyed", "Menyusahkan"],
    ["？", "", "", ""],
    ["几步路", "jǐ bù lù", "just a few steps", "beberapa langkah"],
    ["，", "", "", ""],
    ["有什么好准备的", "yǒu shén me hǎo zhǔn bèi de", "what's there to prepare", "apa yang perlu disiapkan"],
    ["！”", "", "", ""],
    ["她也笑了", "tā yě xiào le", "She also laughed", "Dia juga ketawa"],
    ["，", "", "", ""],
    ["坐在", "zuò zài", "sat", "duduk di"],
    ["我身边", "wǒ shēn biān", "beside me", "sisi saya"],
    ["，", "", "", ""],
    ["絮絮叨叨地", "xù xù dāo dāo de", "chattering", "bercakap tanpa henti"],
    ["说着", "shuō zhe", "saying", "berkata"],
    ["：", "", "", ""],
    ["“", "", "", ""],
    ["看完菊花", "kàn wán jú huā", "After seeing the chrysanthemums", "Selepas melihat bunga kekwa"],
    ["，", "", "", ""],
    ["咱们就去", "zán men jiù qù", "we'll go", "kita pergi"],
    ["‘", "", "", ""],
    ["仿膳", "fǎng shàn", "Fangshan", "Fangshan"],
    ["’", "", "", ""],
    ["，", "", "", ""],
    ["你小时候", "nǐ xiǎo shí hou", "when you were little", "masa awak kecil"],
    ["最爱吃", "zuì ài chī", "loved eating", "paling suka makan"],
    ["那儿的", "nà r de", "there", "di sana"],
    ["豌豆黄儿", "wān dòu huáng r", "pea flour cake", "kek tepung kacang"],
    ["。", "", "", ""],
    ["还记得", "hái jì de", "Remember", "Masih ingat"],
    ["那回", "nà huí", "that time", "masa itu"],
    ["我带你去北海吗", "wǒ dài nǐ qù běi hǎi ma", "when I took you to Beihai", "saya bawa awak ke Beihai"],
    ["？", "", "", ""],
    ["你偏说", "nǐ piān shuō", "you insisted", "awak berkeras"],
    ["那杨树花", "nà yáng shù huā", "that poplar flower", "bunga pokok poplar"],
    ["是毛毛虫", "shì máo máo chóng", "was a caterpillar", "ialah ulat bulu"],
    ["，", "", "", ""],
    ["跑着", "pǎo zhe", "running", "berlari"],
    ["，", "", "", ""],
    ["一脚", "yì jiǎo", "with one foot", "sekaki"],
    ["踩扁一个", "cǎi biǎn yí gè", "stepped on one", "memijak satu"],
    ["……”", "", "", ""],
    ["她", "tā", "She", "Dia"],
    ["忽然不说了", "hū rán bù shuō le", "suddenly stopped", "tiba-tiba berhenti"],
    ["。", "", "", ""],
    ["对于", "duì yú", "For", "Bagi"],
    ["“", "", "", ""],
    ["跑", "pǎo", "run", "lari"],
    ["”", "", "", ""],
    ["和", "hé", "and", "dan"],
    ["“", "", "", ""],
    ["踩", "cǎi", "step", "pijak"],
    ["”", "", "", ""],
    ["一类的字眼儿", "yí lèi de zì yǎn r", "such words", "perkataan sebegini"],
    ["，", "", "", ""],
    ["她比", "tā bǐ", "she was more", "dia lebih"],
    ["我", "wǒ", "than me", "saya"],
    ["还敏感", "hái mǐn gǎn", "sensitive", "sensitif"],
    ["。", "", "", ""],
    ["她又", "tā yòu", "She again", "Dia lagi"],
    ["悄悄地", "qiāo qiāo de", "quietly", "secara senyap"],
    ["出去了", "chū qù le", "went out", "keluar"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第4段

    ["她出去了", "tā chū qù le", "She went out", "Dia keluar"],
    ["，", "", "", ""],
    ["就", "jiù", "and", "lalu"],
    ["再也没回来", "zài yě méi huí lái", "never came back", "tidak pernah kembali"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第5段

    ["邻居们", "lín jū men", "The neighbors", "Jiran-jiran"],
    ["把", "bǎ", "", ""],
    ["她抬上车时", "tā tái shàng chē shí", "when they carried her into the car", "semasa mengangkatnya ke kereta"],
    ["，", "", "", ""],
    ["她还在", "tā hái zài", "she was still", "dia masih"],
    ["大口大口地", "dà kǒu dà kǒu de", "in large mouthfuls", "dengan banyak"],
    ["吐着", "tǔ zhe", "vomiting", "muntah"],
    ["鲜血", "xiān xuè", "blood", "darah"],
    ["。", "", "", ""],
    ["我没想到", "wǒ méi xiǎng dào", "I didn't expect", "Saya tidak menyangka"],
    ["她已经", "tā yǐ jīng", "she was already", "dia sudah"],
    ["病成那样", "bìng chéng nà yàng", "that ill", "sakit begitu"],
    ["。", "", "", ""],
    ["看着", "kàn zhe", "watching", "melihat"],
    ["三轮车", "sān lún chē", "the tricycle", "trikel"],
    ["远去", "yuǎn qù", "go far away", "pergi jauh"],
    ["，", "", "", ""],
    ["也", "yě", "and", "dan"],
    ["绝没想到", "jué méi xiǎng dào", "never expected", "tidak pernah menyangka"],
    ["那竟", "nà jìng", "that would", "itu rupanya"],
    ["是", "shì", "be", "ialah"],
    ["永远的诀别", "yǒng yuǎn de jué bié", "the eternal farewell", "perpisahan yang kekal"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第6段

    ["邻居的", "lín jū de", "The neighbor's", "Jiran punya"],
    ["小伙子", "xiǎo huǒ zi", "young man", "pemuda"],
    ["背着", "bèi zhe", "carried", "mendukung"],
    ["我去看", "wǒ qù kàn", "me to see", "saya pergi melihat"],
    ["她的时候", "tā de shí hou", "her", "dia"],
    ["，", "", "", ""],
    ["她正", "tā zhèng", "she was", "dia sedang"],
    ["艰难地", "jiān nán de", "with difficulty", "dengan susah"],
    ["呼吸着", "hū xī zhe", "breathing", "bernapas"],
    ["，", "", "", ""],
    ["像", "xiàng", "like", "seperti"],
    ["她那一生", "tā nà yì shēng", "her life", "kehidupannya"],
    ["艰难的", "jiān nán de", "difficult", "susah"],
    ["生活", "shēng huó", "life", "kehidupan"],
    ["。", "", "", ""],
    ["别人", "bié rén", "Others", "Orang lain"],
    ["告诉", "gào su", "told", "memberitahu"],
    ["我", "wǒ", "me", "saya"],
    ["，", "", "", ""],
    ["她昏迷前的", "tā hūn mí qián de", "before she fell into a coma", "sebelum dia koma"],
    ["最后一句话", "zuì hòu yí jù huà", "last words", "kata-kata terakhir"],
    ["是", "shì", "were", "ialah"],
    ["：", "", "", ""],
    ["“", "", "", ""],
    ["我那个", "wǒ nà ge", "My", "Saya punya"],
    ["有病的儿子", "yǒu bìng de ér zi", "sick son", "anak lelaki yang sakit"],
    ["和", "hé", "and", "dan"],
    ["我那个", "wǒ nà ge", "my", "saya punya"],
    ["还未成年的女儿", "hái wèi chéng nián de nǚ ér", "underage daughter", "anak perempuan yang belum dewasa"],
    ["……”", "", "", ""],

    ["\n", "", "", ""], // 👈 第7段

    ["又是秋天", "yòu shì qiū tiān", "It was autumn again", "Musim luruh lagi"],
    ["，", "", "", ""],
    ["妹妹", "mèi mei", "my younger sister", "adik perempuan"],
    ["推着", "tuī zhe", "pushed", "menolak"],
    ["我", "wǒ", "me", "saya"],
    ["去北海", "qù běi hǎi", "to Beihai", "ke Beihai"],
    ["看了菊花", "kàn le jú huā", "to see the chrysanthemums", "melihat bunga kekwa"],
    ["。", "", "", ""],
    ["黄色的花", "huáng sè de huā", "Yellow flowers", "Bunga kuning"],
    ["淡雅", "dàn yǎ", "elegant", "anggun"],
    ["，", "", "", ""],
    ["白色的花", "bái sè de huā", "white flowers", "bunga putih"],
    ["高洁", "gāo jié", "noble and pure", "mulia dan suci"],
    ["，", "", "", ""],
    ["紫红色的花", "zǐ hóng sè de huā", "purple-red flowers", "bunga ungu-merah"],
    ["热烈而深沉", "rè liè ér shēn chén", "passionate and profound", "bersemangat dan mendalam"],
    ["，", "", "", ""],
    ["泼泼洒洒", "pō pō sǎ sǎ", "in full bloom", "mekar dengan subur"],
    ["，", "", "", ""],
    ["秋风中", "qiū fēng zhōng", "in the autumn wind", "dalam angin musim luruh"],
    ["正开得烂漫", "zhèng kāi de làn màn", "blooming brilliantly", "sedang mekar dengan meriah"],
    ["。", "", "", ""],
    ["我懂得", "wǒ dǒng de", "I understand", "Saya faham"],
    ["母亲", "mǔ qīn", "Mother's", "Ibu punya"],
    ["没有说完的话", "méi yǒu shuō wán de huà", "unfinished words", "kata-kata yang tidak sempat dihabiskan"],
    ["。", "", "", ""],
    ["妹妹也懂", "mèi mei yě dǒng", "My sister also understands", "Adik pun faham"],
    ["。", "", "", ""],
    ["我俩", "wǒ liǎ", "The two of us", "Kami berdua"],
    ["在一块儿", "zài yī kuài r", "together", "bersama"],
    ["，", "", "", ""],
    ["要", "yào", "should", "hendak"],
    ["好好儿活", "hǎo hǎo r huó", "live well", "hidup dengan baik"],
    ["……", "", "", ""],

    ["\n", "", "", ""], // 👈 出处

    ["（", "", "", ""],
    ["史铁生", "shǐ tiě shēng", "Shi Tiesheng", "Shi Tiesheng"],
    ["《", "", "", ""],
    ["秋天的怀念", "qiū tiān de huái niàn", "Autumn Remembrance", "Kenangan Musim Luruh"],
    ["》", "", "", ""],
    ["，", "", "", ""],
    ["有", "yǒu", "with", "ada"],
    ["改动", "gǎi dòng", "adaptations", "ubah suai"],
    ["）", "", "", ""]
];
